### ISSUE TITLE
setup i18n

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#27]
https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by maxwai** [comment]
Akzeptanzkriterien:

Als Spieler will ich die Website in Deutsch oder English sehen können.  
Als Quest-Creator will ich die Möglichkeit haben das Escape Game auch in English zu schreiben 

- Die Website sollte beim ersten Besuch automatisch auf Deutsch oder English wechseln
- Es soll die Möglichkeit geben manuell die Sprache zu wechseln
- Beim Studio soll es ein Button geben um auf Multi-Language zu wechseln um gleichzeitig Deutsch und English einzugeben
