### ISSUE TITLE
Printable QR Codes with link to game

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#30]
Let game creators export the QR Code with the link to the game in different formats (SVG, PNG, A4 Page with Name and re:quest Logo)

**Comment by Bes0mar** [comment]
Akzeptanzkriterien:

Als Spieler will ich über einen QR Code in das Spiel gelangen.
Als Quest-Creator will ich für mein Spiel einen QR Code als .

Die Website sollte beim ersten Besuch automatisch auf Deutsch oder English wechseln
Es soll die Möglichkeit geben manuell die Sprache zu wechseln
