### ISSUE TITLE
Create Number Input Quest

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#35]
Create a Quest with the following properties

__Edit View__
Question: text input
Answer: number input

__Play View__
Question: text element
Answer: number input

**Comment by cleenc0de** [comment]
Akzeptanzkriterien:

Als Nutzer möchte ich im Studio Zahleneingabe-Quests für mein re:quest erstellen und bearbeiten können.
Als Spieler möchte ich Zahleneingabe-Quests beantworten können. 

-  Zahleneingabe-Quest kann zu einem Raum eines re:quests hinzugefügt werden
- warnt dich, falls du keine Zahl als Antwort angegeben hast
- lässt dich bei Warnung nicht abspeichern/antworten (in Bearbeitungs- und Spielsicht)
