### ISSUE TITLE
Create multiple choice quest

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#36]
Create a Quest with the following properties

__Edit View__
Question: text input
Answers: 
- 1 correct text input
- 1-n wrong text inputs

__Play View__
Question: text element
Answer: clickable answers

**Comment by AbtinDarbandy** [comment]
Akzeptanzkriterien:  
  
Als Nutzer möchte ich die Möglichkeit haben Multiple-Choice-Fragen für meinen Re:quest zu erstellen.
  
- Die Multiple-Choice Aufgabe soll im re:quest Studio zur Auswahl stehen  
- Unter jeder Wahlmöglichkeit soll ein Text hinzufügbar sein
- Die Auswahl der richtigen Antwort sollte über Radial Buttons (Checkboxes) möglich sein.
