### ISSUE TITLE
Add option to quest to show them only after another quest has been solved

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#39]
Example: When there are quests A, B and C in a room, the creator should have the option to display quest C to users only after quest B has been solved successfully

**Comment by cleenc0de** [comment]
Akzeptanzkriterien:
Als Nutzer möchte ich einstellen können ob ein Quest nach Abschluss eines anderes Quests angezeigt werden soll.  
Als Spieler soll der Quest angezeigt werden nachdem ich den benötigten Quests abgeschlossen habe.  

-
