### ISSUE TITLE
Add YouTube Embed Module

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#45]
Besides quests, we also want to display media. Embedding YouTube videos would be great

**Comment by DenisStocker** [comment]
Akzeptanzkriterien:

Als Spieler will ich Youtube Videos zu komplexeren Aufgaben als Hilfestellung bekommen.

- Die Videos sollen sich automatisch an verschiedene Displaygrößen anpassen.
- Unwichtige Teile am Anfang oder am Ende des Videos sollen übersprungen werden.
- Videos sollen im Vollbildmodus verfügbar sein.
