### ISSUE TITLE
Add Image Media Module

### ISSUE THREAD

**Issue by felixerdy** [re-quest-team/request#47]
Besides quests, we also want to display media. Embedding images would be great

**Comment by DenisStocker** [comment]
Akzeptanzkriterien:
Als Studionutzer möchte ich Bilder in meinen quests einbauen.
- Das Bild soll über eine URL eingefügt werden.
- Das BIld soll beschriftet werden können.

Als Spieler möchte ich Bilder angezeigt bekommen.
- Das Bild soll sich an Bildschirmgrößen anpassen.
